serviceAccount:
  create: false

config:
  prometheus:
    enabled: false
  network:
    id: 25
    name: xplor-24
    shortname: xplor-24
    currency:
      name: Ether
      symbol: ETH 
      decimals: 18
      dualToken: false
  account:
    enabled: false
  testnet: false 

blockscout:
  enabled: true
  image:
    repository: blockscout/blockscout
    pullPolicy: IfNotPresent
    tag: "6.8.0.commit.8ce08ee5"
  init:
    enabled: true
    command:
      - /bin/sh
    args:
      - -c
      - bin/blockscout eval "Elixir.Explorer.ReleaseTasks.create_and_migrate()"
  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 1
      memory: 2Gi
  service:
    type: ClusterIP
    port: 4000
  tls:
    enabled: false
  separateApi:
    enabled: false
    replicaCount: 1
  replicaCount: 1
  podSecurityContext: {}
  postgresql:
    enabled: false
  env:
    ETHEREUM_JSONRPC_VARIANT: geth
    DATABASE_URL: postgresql://postgres:TvQZXCu6ba@postgresql.xplor-24.svc.cluster.local:5432/postgres?ssl=false
    ETHEREUM_JSONRPC_HTTP_URL: http://goquorum-node-validator-2.obi-quorum.svc.cluster.local:8545
    ETHEREUM_JSONRPC_TRACE_URL: http://goquorum-node-validator-3.obi-quorum.svc.cluster.local:8545
  extraEnv: []
  command:
    - /bin/sh
  args:
    - -c
    - bin/blockscout start
  envFromSecret: []
  envFrom: []
  securityContext: {}
  readinessProbe:
    enabled: true
    path: /api/v1/health/readiness
    params:
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 60
  livenessProbe:
    enabled: true
    path: /api/v1/health/liveness
    params:
      initialDelaySeconds: 100
      periodSeconds: 100
      timeoutSeconds: 30
  terminationGracePeriodSeconds: 300
  ingress:
    enabled: true
    className: ""
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/rewrite-target: /
    hostname: ""
    tls:
      enabled: false
    paths:
      - path: /
        pathType: Prefix

podAnnotations: {}
imagePullSecrets: []

