# Default values for verification-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# ghcr.io/blockscout/smart-contract-verifier:main
replicaCount: 1

image:
  repository: ghcr.io/blockscout/smart-contract-verifier
  pullPolicy: IfNotPresent
  tag: "main"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8050

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /healthz
    port: http
readinessProbe:
  httpGet:
    path: /healthz
    port: http

# Additional volumes on the output Deployment definition.
volumes:
  - name: config-volume
    configMap:
      name: smart-contract-verifier-config
  - name: compilers-volume
    emptyDir: {}

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
  - name: config-volume
    mountPath: /app/config.toml
    subPath: config.toml
  - name: compilers-volume
    mountPath: /tmp/compilers

nodeSelector: {}

tolerations: []

affinity: {}
